import assert from 'node:assert/strict';
import { test } from 'node:test';

import { parseCargoLockfile, parseCargoToml } from '../src/adapters/build-system/cargo.js';
import type { ScannedFile } from '../src/types.js';

// Cargo.lock transitive dependency resolution mirrors the npm package-lock
// graph: external (sourced) packages become proven lockfile:transitive deps;
// local workspace members (no `source`) are left for first-class resolution.

function file(relativePath: string, content: string): ScannedFile {
  return { absolutePath: `/repo/${relativePath}`, relativePath, content, hash: 'h', language: 'toml' };
}

const LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "serde_derive"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

test('parseCargoLockfile emits sourced packages as proven transitive deps and skips local members', () => {
  const parsed = parseCargoLockfile(file('Cargo.lock', LOCK));

  assert.equal(parsed.manifestPath, 'Cargo.toml');
  assert.deepEqual(
    parsed.dependencies.map((d) => [d.name, d.version, d.dependencyType, d.confidence]),
    [
      ['serde', '1.0.200', 'lockfile:transitive', 'proven'],
      ['serde_derive', '1.0.200', 'lockfile:transitive', 'proven']
    ]
  );
  // "myapp" has no source (local crate) -> excluded.
  assert.ok(!parsed.dependencies.some((d) => d.name === 'myapp'));
});

test('parseCargoToml merges lockfile transitive deps without duplicating manifest deps', () => {
  const manifest = file(
    'Cargo.toml',
    '[package]\nname = "myapp"\nversion = "0.1.0"\n\n[dependencies]\nserde = "1"\n'
  );
  const lockfile = parseCargoLockfile(file('Cargo.lock', LOCK));

  const parsed = parseCargoToml(manifest, undefined, lockfile);

  const serde = parsed.dependencies.filter((d) => d.name === 'serde');
  assert.equal(serde.length, 1, 'serde appears once (manifest wins over lockfile)');
  assert.equal(serde[0]!.dependencyType, 'dependencies');
  const derive = parsed.dependencies.find((d) => d.name === 'serde_derive');
  assert.ok(derive, 'transitive serde_derive added from lockfile');
  assert.equal(derive.dependencyType, 'lockfile:transitive');
});

test('parseCargoToml without a lockfile is unchanged', () => {
  const manifest = file(
    'Cargo.toml',
    '[package]\nname = "myapp"\nversion = "0.1.0"\n\n[dependencies]\nserde = "1"\n'
  );
  const parsed = parseCargoToml(manifest, undefined);
  assert.deepEqual(parsed.dependencies.map((d) => d.name), ['serde']);
});
