import assert from 'node:assert/strict';
import { test } from 'node:test';

import { parsePoetryLockfile, parsePyprojectToml } from '../src/adapters/build-system/python.js';
import type { ScannedFile } from '../src/types.js';

// poetry.lock transitive dependency resolution mirrors the Cargo.lock path:
// resolved packages become proven lockfile:transitive deps; local directory/file
// sources are skipped so they stay first-class packages.

function file(relativePath: string, content: string): ScannedFile {
  return { absolutePath: `/repo/${relativePath}`, relativePath, content, hash: 'h', language: 'toml' };
}

const LOCK = `# This file is automatically @generated by Poetry.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."

[[package]]
name = "mylocal"
version = "0.1.0"
description = "local path dep"

[package.source]
type = "directory"
url = "../mylocal"

[[package]]
name = "urllib3"
version = "2.0.7"
description = "HTTP library"
`;

test('parsePoetryLockfile emits resolved packages as proven transitive deps and skips local sources', () => {
  const parsed = parsePoetryLockfile(file('poetry.lock', LOCK));

  assert.equal(parsed.manifestPath, 'pyproject.toml');
  assert.deepEqual(
    parsed.dependencies.map((d) => [d.name, d.version, d.dependencyType, d.confidence]),
    [
      ['requests', '2.31.0', 'lockfile:transitive', 'proven'],
      ['urllib3', '2.0.7', 'lockfile:transitive', 'proven']
    ]
  );
  assert.ok(!parsed.dependencies.some((d) => d.name === 'mylocal'), 'local directory source skipped');
});

test('parsePyprojectToml merges poetry lockfile transitive deps without duplicating manifest deps', () => {
  const manifest = file(
    'pyproject.toml',
    '[project]\nname = "myapp"\nversion = "0.1.0"\ndependencies = ["requests>=2"]\n'
  );
  const lockfile = parsePoetryLockfile(file('poetry.lock', LOCK));

  const parsed = parsePyprojectToml(manifest, lockfile);

  const requests = parsed.dependencies.filter((d) => d.name === 'requests');
  assert.equal(requests.length, 1, 'requests appears once (manifest wins)');
  assert.equal(requests[0]!.dependencyType, 'dependencies');
  const urllib3 = parsed.dependencies.find((d) => d.name === 'urllib3');
  assert.ok(urllib3, 'transitive urllib3 added from lockfile');
  assert.equal(urllib3.dependencyType, 'lockfile:transitive');
});

test('parsePyprojectToml without a lockfile is unchanged', () => {
  const manifest = file(
    'pyproject.toml',
    '[project]\nname = "myapp"\nversion = "0.1.0"\ndependencies = ["requests>=2"]\n'
  );
  const parsed = parsePyprojectToml(manifest);
  assert.deepEqual(parsed.dependencies.map((d) => d.name), ['requests']);
});
