import {
  escapeRegExp,
  isGeneratedProtobufFilePath,
  sourceLinesWithCommentMasks
} from './shared.js';

export function firstMatchingProtobufRpcLine(content: string, filePath: string, routePath: string): string | undefined {
  if (isGeneratedProtobufFilePath(filePath) || isGeneratedProtobufContent(content)) return undefined;
  const target = parseProtobufRoutePath(routePath);
  if (target === undefined) return undefined;
  const lines = sourceLinesWithCommentMasks(content);
  const fullPathLine = lines.find((line) => protobufFullPathMatches(line.masked, target.serviceName, target.rpcName));
  if (fullPathLine !== undefined) return fullPathLine.raw.trim();
  const maskedContent = lines.map((line) => line.masked).join('\n');
  if (!protobufServiceContextMatches(maskedContent, target.serviceName)) return undefined;
  const rpcLine = lines.find((line) => protobufRpcCallLineMatches(line.masked, target.rpcName));
  return rpcLine === undefined ? undefined : rpcLine.raw.trim();
}

function isGeneratedProtobufContent(content: string): boolean {
  const header = content.slice(0, 4096);
  return /(?:^|\n)\s*(?:(?:\/\/|#|\/\*)\s*)?(?:@generated\b|Code generated .* DO NOT EDIT\.?|Generated by the protocol buffer compiler\.?|Generated by protoc|Generated from protobuf schema|This file was generated by)/i.test(header) ||
    /\bprotoc-gen-(?:connect|es|go|grpc|js|ts)\b/i.test(header);
}

function parseProtobufRoutePath(routePath: string): { serviceName: string; rpcName: string } | undefined {
  const match = /^([A-Za-z_]\w*)\/([A-Za-z_]\w*)$/.exec(routePath);
  if (!match) return undefined;
  return {
    serviceName: match[1]!,
    rpcName: match[2]!
  };
}

function protobufFullPathMatches(line: string, serviceName: string, rpcName: string): boolean {
  const pattern = new RegExp(`(?:^|[^A-Za-z0-9_.])/?(?:[A-Za-z_]\\w*\\.)*${escapeRegExp(serviceName)}/${escapeRegExp(rpcName)}\\b`);
  return pattern.test(line);
}

function protobufServiceContextMatches(content: string, serviceName: string): boolean {
  const pattern = new RegExp(`\\b${escapeRegExp(serviceName)}(?:Grpc|Client|Stub|BlockingStub|FutureStub|CoroutineStub)?\\b`);
  return pattern.test(content);
}

function protobufRpcCallLineMatches(line: string, rpcName: string): boolean {
  return protobufRpcNameVariants(rpcName).some((variant) => {
    const pattern = new RegExp(`(?:\\.|::)\\s*${escapeRegExp(variant)}\\s*\\(`);
    return pattern.test(line);
  });
}

function protobufRpcNameVariants(rpcName: string): string[] {
  return uniqueStrings([
    rpcName,
    lowerFirst(rpcName),
    camelToSnakeCase(rpcName)
  ]);
}

function lowerFirst(value: string): string {
  return value.length === 0 ? value : value[0]!.toLowerCase() + value.slice(1);
}

function camelToSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function uniqueStrings(values: string[]): string[] {
  return [...new Set(values.filter((value) => value.length > 0))];
}
