import { execFileSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';

export type ParallaxGitHookName = 'pre-commit' | 'pre-push';
export type ParallaxGitHookAction = 'create' | 'overwrite' | 'skip';

export type ParallaxGitHookOptions = {
  repoRoot: string;
  hooks?: ParallaxGitHookName[];
  failOn?: string;
  command?: string;
  force?: boolean;
};

export type PlannedParallaxGitHook = {
  hook: ParallaxGitHookName;
  path: string;
  action: ParallaxGitHookAction;
  content: string;
};

export type ParallaxGitHookPlan = {
  repoRoot: string;
  hooks: PlannedParallaxGitHook[];
};

const MANAGED_MARKER = 'parallax-managed-hook';
const DEFAULT_HOOKS: ParallaxGitHookName[] = ['pre-commit'];

export function planParallaxGitHooks(options: ParallaxGitHookOptions): ParallaxGitHookPlan {
  const repoRoot = resolve(options.repoRoot);
  assertGitRepo(repoRoot);
  const hooks = options.hooks ?? DEFAULT_HOOKS;
  const planned = hooks.map((hook) => {
    const path = resolveHookPath(repoRoot, hook);
    const exists = existsSync(path);
    const existing = exists ? readFileSync(path, 'utf8') : '';
    const managed = existing.includes(MANAGED_MARKER);
    const action: ParallaxGitHookAction = exists
      ? (managed || options.force ? 'overwrite' : 'skip')
      : 'create';
    return {
      hook,
      path,
      action,
      content: hookTemplate(hook, {
        command: options.command ?? 'parallax',
        failOn: options.failOn ?? 'proven'
      })
    };
  });
  return { repoRoot, hooks: planned };
}

export function installParallaxGitHooks(options: ParallaxGitHookOptions): ParallaxGitHookPlan {
  const plan = planParallaxGitHooks(options);
  for (const hook of plan.hooks) {
    if (hook.action === 'skip') continue;
    mkdirSync(dirname(hook.path), { recursive: true });
    writeFileSync(hook.path, hook.content);
    chmodSync(hook.path, 0o755);
  }
  return plan;
}

function assertGitRepo(repoRoot: string): void {
  try {
    execFileSync('git', ['rev-parse', '--git-dir'], { cwd: repoRoot, stdio: 'ignore' });
  } catch {
    throw new Error(`install-hook requires a git repository: ${repoRoot}`);
  }
}

function resolveHookPath(repoRoot: string, hook: ParallaxGitHookName): string {
  const raw = execFileSync('git', ['rev-parse', '--git-path', `hooks/${hook}`], {
    cwd: repoRoot,
    encoding: 'utf8'
  }).trim();
  return isAbsolute(raw) ? raw : resolve(repoRoot, raw);
}

function hookTemplate(
  hook: ParallaxGitHookName,
  options: { command: string; failOn: string }
): string {
  const body = hook === 'pre-commit'
    ? preCommitBody()
    : prePushBody();
  return `#!/bin/sh
# ${MANAGED_MARKER}: ${hook}
# Generated by Parallax. Re-run parallax install-hook to update this file.
set -eu

PARALLAX_BIN=\${PARALLAX_BIN:-${shellSingleQuote(options.command)}}
PARALLAX_FAIL_ON=\${PARALLAX_FAIL_ON:-${shellSingleQuote(options.failOn)}}

if [ "\${PARALLAX_SKIP_HOOK:-}" = "1" ] || [ "\${PARALLAX_HOOK_SKIP:-}" = "1" ]; then
  exit 0
fi

if ! repo_root=$(git rev-parse --show-toplevel 2>/dev/null); then
  exit 0
fi
cd "$repo_root"

${body}
`;
}

function preCommitBody(): string {
  return `changed_files=$(git diff --cached --name-only --diff-filter=ACMR | sed '/^$/d' | paste -sd, -)
if [ -z "$changed_files" ]; then
  exit 0
fi

echo "Parallax: indexing staged impact context..."
"$PARALLAX_BIN" init >/dev/null
"$PARALLAX_BIN" index >/dev/null
"$PARALLAX_BIN" analyze --changed "$changed_files" --fail-on "$PARALLAX_FAIL_ON"
`;
}

function prePushBody(): string {
  return `tmp_file=$(mktemp "\${TMPDIR:-/tmp}/parallax-pre-push.XXXXXX")
trap 'rm -f "$tmp_file"' EXIT

zero_oid=0000000000000000000000000000000000000000
while read local_ref local_oid remote_ref remote_oid
do
  if [ -z "\${local_oid:-}" ] || [ "$local_oid" = "$zero_oid" ]; then
    continue
  fi
  if [ -n "\${remote_oid:-}" ] && [ "$remote_oid" != "$zero_oid" ]; then
    git diff --name-only --diff-filter=ACMR "$remote_oid...$local_oid" >> "$tmp_file"
  fi
done

if [ ! -s "$tmp_file" ]; then
  base_ref="\${PARALLAX_BASE:-}"
  if [ -z "$base_ref" ]; then
    upstream=$(git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null || true)
    if [ -n "$upstream" ]; then
      base_ref=$(git merge-base HEAD "$upstream" 2>/dev/null || true)
    fi
  fi
  if [ -z "$base_ref" ]; then
    base_ref=$(git merge-base HEAD origin/main 2>/dev/null || true)
  fi
  if [ -z "$base_ref" ]; then
    echo "Parallax: no push base found; set PARALLAX_BASE to enable pre-push impact gating." >&2
    exit 0
  fi
  git diff --name-only --diff-filter=ACMR "$base_ref...HEAD" >> "$tmp_file"
fi

changed_files=$(sort -u "$tmp_file" | sed '/^$/d' | paste -sd, -)
if [ -z "$changed_files" ]; then
  exit 0
fi

echo "Parallax: indexing push impact context..."
"$PARALLAX_BIN" init >/dev/null
"$PARALLAX_BIN" index >/dev/null
"$PARALLAX_BIN" analyze --changed "$changed_files" --fail-on "$PARALLAX_FAIL_ON"
`;
}

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
